# Generated by Django 5.0.3 on 2024-03-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dislike_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
