# Generated by Django 5.0.3 on 2024-03-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
